package ninepatch.game;

public enum Building {
    CraftingStation,
    Torch,
    CrystalLamp,
    WoodSign,
    FlagPole,
    Smelter,
    ScienceLab,
    ConstructionYard,
    WoodFloor,
    BarrierWall,
    MetalWall,
    Gate,
    RockPile,
    StonePath,
    PavementFloor,
    PavementStripedFloor,
    GardenPatch,
    StorageCrate,
    Generator,
    SolarPanel,
    // WideSolar,
    // TwoByTwoBase,
    Conduit,
    PowerSwitch,
    LightSensor,
    Battery,
    Battery2,
    HabitatModule,
    AirCleaner,
    Airlock,
    AutoAirlock,
    StoragePile,
    ChemistryLab,
    // NpcHome,
    FloodLight,
    GreenHouse,
    WindTurbine,
    WaterSupply,
    Garage,
    NavLight,
    CommsTower,
    MedBay,
    Recycler,
    RecyclerOrig,
    RepairDroneBase,
    CraftingBot,
    MiningRig,
    Rtg,
    LightningCollector,
    WallLight,
    RainCollector,
    AutoRainCollector,
    WaterSpigot,
    Explosive,
    GravelFloor,
    WorkbenchHabitat,
    AdvancedFabricator,
    Refinery,
    FuelTank,
    LaunchPad,
    MagicPower
}
